[build]
  command = "jekyll build"
  publish = "_site"
  functions = "functions"

[[redirects]]
  from = "/api/quote_generator"
  to = "/.netlify/functions/quote_generator"
  status = 200
  force = true
